### ISSUE TITLE
Wrong country for code "7".

### ISSUE THREAD

**Issue by Desmuz** [SURYAKANTSHARMA/CountryPicker#75]
In last changes "KZ": "7" and "RU": "7". But right KZ is "77" and "76".

**Comment by SURYAKANTSHARMA** [comment]
@Desmuz  could you please raise PR because I am confused now because google showing both ("KZ" and "RU") have dialling code with +7

<img width="717" alt="Screenshot 2021-05-16 at 5 42 56 PM" src="https://user-images.githubusercontent.com/6416095/118396686-3febae00-b66e-11eb-9711-ca787afb5b4b.png">

<img width="602" alt="Screenshot 2021-05-16 at 5 43 04 PM" src="https://user-images.githubusercontent.com/6416095/118396672-2d717480-b66e-11eb-9522-15d6dee54ca8.png">

**Comment by freakdragon** [comment]
No. 7 is country code, next number is city number code (not country code). Most of another similar libraries (Android and iOS) use 7 as phone code for Kazakhstan. If there are 76 and 77 codes then there is no sense to use 77, IMHO.

**Comment by freakdragon** [comment]
@SURYAKANTSHARMA that's normal that Kazakhstan and Russia have the same phone numbers. Those countries have close relations. You can read some books about the collapse of the USSR and time after it if you are interested.

**Comment by Sharkesm** [comment]
@freakdragon @SURYAKANTSHARMA Let's close this issue if there are no changes meant to be made at this stage.
